### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MihayloPupin** [Haggets/source-armature-toolkit#1]
**Describe the bug**
Armature Renaming function return error in Blender console when try to convert from Source Default Scheme to Blender Scheme. Main bones come renamed, and helpers Trapezius L & R and Shoulder L. But Shoulder R and other helpers Ulna, Wrist, Elbow, Knee and Pectoral L&R no. None of VertexGroups come renamed. Restore button stay inactive.

Renaming applied on default Alyx Vance armature from HL2 Ep2.

**Steps to reproduce behavior**
(1. Go to 'Source Armature Toolkit -> Armature Renaming' on Plugin Panel
2. Click on 'Convert'
3. See error)

**Expected behavior**
(A clear and concise description of what you expected to happen.)

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/108688623/177198540-6a4b7fab-a0c6-4f73-bb35-40ea611cd9d8.jpg)

**Logs**
Traceback (most recent call last):
  File "C:\Users\shilo\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\source-armature-toolkit-main\ops.py", line 58, in execute
    armature_rename(1)
  File "C:\Users\shilo\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\source-armature-toolkit-main\armature_rename.py", line 72, in armature_rename
    convert(False)
  File "C:\Users\shilo\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\source-armature-toolkit-main\armature_rename.py", line 58, in convert
    rename(prefix, bone, index)
  File "C:\Users\shilo\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\source-armature-toolkit-main\armature_rename.py", line 31, in rename
    armature.pose.bones[prefix + bone].name = prefix + bone.replace(old, '') + new
UnboundLocalError: local variable 'old' referenced before assignment

**Details**:
Blender Version: 3.2

Downloaded through...
- [ ] Main branch
- [X] Release

Release/Addon Version:
1.0.0

**Additional context**

**Comment by Haggets** [comment]
If you really really still want to fix the problem. Please send me the blend file so i take a closer look.
